[project]
name = "espen-sql-api"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.14.0",
    "fastapi>=0.115.4",
    "orjson>=3.10.16",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.9.2",
    "pyodbc>=5.2.0",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.36",
    "sqlglot>=25.29.0",
    "uvicorn>=0.32.0",
]

[dependency-groups]
dev = [
    "ruff"
]
